#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
Created on Tue Nov  6 22:14:33 2018

@author: katezeng

This module is for histograms and correlations
    - Use a histogram to plot at least three (3) of the variables (attributes) in either dataset. Discuss the insight generated by the histograms. 
      What do they show or suggest?
    - Identify three (3) quantitative variables from either data set. Find the correlation between all the pairs of these quantity variables. 
      Include a table of the output in your report, and explain your findings – what does this indicate about your data? Use scatterplots to 
      display the results. Ideally, create a set of scatterplot subplots.
"""

import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from sklearn import preprocessing
def histgram():
    #find and merge the mean airbnb price corresonding to zipcode 
    df=pd.read_csv('Airbnb_Cleaned.csv')
    grouped = df['price'].groupby(df['zipcode'])
    x=grouped.mean()
    df1=pd.DataFrame({'zipcode':x.index, 'mean_price':x.values})
    df = pd.merge(df, df1,on= ['zipcode'])
    
    #choose three variables and plot histogram
    accommodates=df['accommodates']
    mean_price=df['mean_price']
    bedroom=df['bedrooms']
    legend = ['Airbnb mean_price', 'hotel_meanprice','hotel_minprice']
    guest_included=df['guests_included']
    bath=df['bathrooms']
    hotel_price=df['hotel_meanprice']
    hotel_min=df['hotel_minprice']

    plt.hist([mean_price,hotel_price,hotel_min], color=['blue','green','red'],bins=10)
    plt.xlabel("Number")
    plt.ylabel("Frequency")
    plt.legend(legend)
    plt.title('Airbnb and hotel price on the market')
    plt.show()
def normalization(data):
    from sklearn import preprocessing
    import numpy as np
    import pandas as pd
    #normalize the data
    x = data.values #returns a numpy array
    min_max_scaler = preprocessing.MinMaxScaler()
    x_scaled = min_max_scaler.fit_transform(x)
    data = pd.DataFrame(x_scaled)
    return(data)
def correlation():
    import seaborn as sns
    import pandas as pd
    import matplotlib.pyplot as plt
    #find and merge the mean airbnb price corresonding to zipcode 
    df=pd.read_csv('Airbnb_Cleaned.csv')
    grouped = df['price'].groupby(df['zipcode'])
    x=grouped.mean()
    df1=pd.DataFrame({'zipcode':x.index, 'mean_price':x.values})
    df = pd.merge(df, df1,on= ['zipcode'])
    accommodates=df['accommodates']
    mean_price=df['mean_price']
    num_hotel=df['number_hotels']
    hotel_mean_price=df['hotel_meanprice']
    num_res=df['num_res']
    df1=df[['mean_price','hotel_meanprice','number_hotels']]
    #plot the heatmap
    f, ax = plt.subplots(figsize=(10, 6))
    corr = df1.corr()
    hm = sns.heatmap(round(corr,2), annot=True, ax=ax, cmap="coolwarm",fmt='.2f',
                 linewidths=.05)
    f.subplots_adjust(top=0.93)
    t= f.suptitle('Correlation between airbnb mean price, hotel mean price and number of hotels', fontsize=14)
    
    #make a set of subplot
    plt.figure()
    plt.subplot(2,2,1)
    plt.plot(mean_price,hotel_mean_price,'ro')
    plt.title('Airbnb mean price versus mean price of hotel')
    
    plt.subplot(2,2,2)
    plt.plot(mean_price,num_hotel,'ro')
    plt.title('airbnb mean price versus number of hotel')
    
    plt.subplot(2,2,3)
    plt.plot(num_hotel,hotel_mean_price,'ro')
    plt.title('number of hotel versus hotel mean price')
    plt.show()
    


def main():
    histgram()
    correlation()
    
    
    
    
